# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/OPPO/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter OP4EC1,$(TARGET_DEVICE)),)

endif
